"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MyTestComponent = exports.Button = exports.BaseButton = exports.SvgIcon = exports.AddIcon = exports.VerifyIcon = exports.MailIcon = exports.CameraIcon = exports.Typo = void 0;
var index_1 = require("./Typography/index");
Object.defineProperty(exports, "Typo", { enumerable: true, get: function () { return index_1.Typo; } });
var index_2 = require("./Icons/index");
Object.defineProperty(exports, "CameraIcon", { enumerable: true, get: function () { return index_2.CameraIcon; } });
Object.defineProperty(exports, "MailIcon", { enumerable: true, get: function () { return index_2.MailIcon; } });
Object.defineProperty(exports, "VerifyIcon", { enumerable: true, get: function () { return index_2.VerifyIcon; } });
Object.defineProperty(exports, "AddIcon", { enumerable: true, get: function () { return index_2.AddIcon; } });
Object.defineProperty(exports, "SvgIcon", { enumerable: true, get: function () { return index_2.SvgIcon; } });
var index_3 = require("./BaseButton/index");
Object.defineProperty(exports, "BaseButton", { enumerable: true, get: function () { return index_3.BaseButton; } });
var index_4 = require("./Button/index");
Object.defineProperty(exports, "Button", { enumerable: true, get: function () { return index_4.Button; } });
var TestComponent_1 = require("./TestComponent");
Object.defineProperty(exports, "MyTestComponent", { enumerable: true, get: function () { return TestComponent_1.MyTestComponent; } });
